# Generated by Django 3.1 on 2020-12-03 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_auto_20171211_1540'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
